//This program takes text as input, and replaces tab characters with the proper number of space characters

//Note: The actual length of blank space generated by tab character is variable. 

//It depends on the distance from the tab character to the nearest tab stop. 
//Tab stops are fixed line positions (usually a multiple of 8 characters). 
//If tab character is located at, or after a tab stop, the cursor will be moved to the next nearest tab stop.  
//For example, if \t is located at line[0], line[1], ... line[6] the cursor will be moved to line[7],
//if \t located at line[7], ... line[14] the cursor will be moved to line[15], and so on.

#include<stdio.h>

#define MAXLINE 1000
#define TAB_STOP 8

main() {

	char c='a';
	char line[MAXLINE];
	int i, j;
	int tab_length;

	while(c != EOF) { 
 		
		//note the double check for EOF, because to get out of while loop we first need to get out of for loop
		
		for(i=0; (c = getchar()) != EOF && c != '\n'; i++)   
		{			
			tab_length = TAB_STOP - i % TAB_STOP;   //calc the distance to the nearest tab stop (how many spaces)

			if(c == '\t') {
				
				for(j=0; j<tab_length-1; i++, j++)  //tab_length-1 so that we don't increment i twice after 
								    //adding the last space
					
					line[i] = ' ';
				
				line[i] = ' ';                      //that's why the last space is added manually
			}
			else
				line[i] = c;
		
		}
		line[i] = '\0';   //replace newline with NULL
			
		printf("%s\n", line);
	}

}
